// Based on 08/30/2025 documentation at: https://classicuo.org/scripting/namespaces/enums/
// Status: Verified initial AI conversion from documentation and wrapped them into a namespace.
//         I have not verified the individual enum values, but they do no matter because using
//         the correct name allows UOC to provide correct values.

/**
 * @deprecated **WARNING** the non-namespaced version of these enums seem more functional in the UOC editor
 */
declare namespace enums {

    /**
     * Abilities enumeration
     * Represents various character abilities and states
     */
    declare enum Abilities {
        AchievePerfection = 1009,
        ActiveMeditation = 1013,
        Agility = 1045,
        AnimalForm = 1034,
        AnticipateHit = 1147,
        ArcaneEmpowerment = 1026,
        ArchProtection = 1030,
        ArmorPierce = 1121,
        AttuneWeapon = 1021,
        AuraOfNausea = 1110,
        BarakoDraftOfMight = 1173,
        BarrabHemolymphConcentrate = 1170,
        Berserk = 1052,
        Bleed = 1039,
        Bless = 1048,
        Block = 1066,
        BloodOathCaster = 1014,
        BloodOathCurse = 1015,
        BloodwormAnemia = 1115,
        Boarding = 1166,
        Bodyguard = 1151,
        BoneBreaker = 1178,
        BoneBreakerImmune = 1181,
        CaddelliteInfused = 1186,
        CalledShot = 1140,
        CityTradeDeal = 1126,
        Clumsy = 1040,
        CombatTraining = 1160,
        Conduit = 1143,
        Confidence = 1093,
        ConsecrateWeapon = 1082,
        CorpseSkin = 1016,
        CounterAttack = 1095,
        CriminalStatus = 1120,
        Cunning = 1046,
        Curse = 1043,
        CurseWeapon = 1088,
        DeathRay = 1154,
        DeathRayDebuff = 1155,
        DeathStrike = 1006,
        DefenseMastery = 1067,
        DespairCaster = 1068,
        DespairTarget = 1060,
        Disarm = 1077,
        Disguised = 1033,
        DismountPrevention = 1001,
        DivineFury = 1010,
        DragonTurtleDebuff = 1165,
        DualWield = 1065,
        ElementalFury = 1138,
        ElementalFuryDebuff = 1139,
        Enchant = 1091,
        EnchantedSummoning = 1157,
        EnemyOfOne = 1011,
        EnemyOfOneDebuff = 1084,
        EssenceOfWind = 1023,
        EtherealBurst = 1144,
        EtherealVoyage = 1024,
        Evasion = 1094,
        EvilOmen = 1007,
        FactionStatLoss = 1118,
        FanDancerFanFire = 1105,
        FeebleMind = 1041,
        Feint = 1079,
        FeintDebuff = 1185,
        FishPie = 1062,
        FistsOfFury = 1169,
        Fly = 1054,
        FocusedEye = 1136,
        ForceArrow = 1076,
        GazeDespair = 1112,
        GiftOfLife = 1025,
        GiftOfRenewal = 1020,
        GrapesOfWrath = 1083,
        Healing = 1069,
        HeatOfBattleStatus = 1119,
        HeightenedSenses = 1152,
        HidingAndOrStealth = 1012,
        HiryuPhysicalResistance = 1113,
        HitLowerAttack = 1063,
        HitLowerDefense = 1064,
        HonorableExecution = 1092,
        Honored = 1103,
        HonoredDebuff = 1008,
        HorrificBeast = 1085,
        HowlOfCacophony = 1111,
        Humility = 1129,
        HumilityDebuff = 1127,
        ImmolatingWeapon = 1090,
        Incognito = 1032,
        InjectedStrike = 1162,
        InjectedStrikeDebuff = 1161,
        Inspire = 1055,
        Intuition = 1156,
        Invigorate = 1056,
        Invisibility = 1036,
        JukariBurnPoiltice = 1171,
        Knockout = 1141,
        KurakAmbushersEssence = 1172,
        LichForm = 1086,
        LightningStrike = 1096,
        MagicReflection = 1031,
        ManaPhase = 1104,
        ManaShield = 1146,
        MassCurse = 1044,
        MassSleep = 1053,
        MedusaStone = 1108,
        Mindrot = 1017,
        MomentumStrike = 1097,
        MortalStrike = 1027,
        MysticWeapon = 1145,
        MysticalPolymorphTotem = 1188,
        NightSight = 1005,
        NoRearm = 1002,
        Onslaught = 1137,
        OrangePetals = 1098,
        PainSpike = 1018,
        Paralyze = 1037,
        Perfection = 1102,
        Perseverance = 1058,
        Pierce = 1134,
        PlayingTheOdds = 1135,
        PlayingTheOddsDebuff = 1164,
        Poison = 1038,
        PoisonImmunity = 1100,
        Polymorph = 1035,
        Potency = 1167,
        PotionGloriousFortune = 1187,
        Protection = 1029,
        PsychicAttack = 1081,
        Rage = 1106,
        RageFocusingBuff = 1073,
        RageFocusingDebuff = 1072,
        Rampage = 1130,
        ReactiveArmor = 1028,
        ReaperForm = 1089,
        Resilience = 1057,
        RoseOfTrinsic = 1099,
        RotwormBloodDisease = 1116,
        RuneBeetleCorruption = 1114,
        SakkhraProphylaxis = 1175,
        SavingThrow = 1142,
        Shadow = 1149,
        ShieldBash = 1158,
        SkillUseDelay = 1117,
        Sleep = 1049,
        Sparks = 1176,
        SpellFocusingBuff = 1070,
        SpellFocusingDebuff = 1071,
        SpellPlague = 1051,
        Spirituality = 1128,
        SplinteringEffect = 1122,
        Stagger = 1131,
        StoneForm = 1050,
        Strangle = 1019,
        Strength = 1047,
        Surge = 1078,
        Swarm = 1177,
        SwarmImmune = 1180,
        SwingSpeedDebuff = 1123,
        TalonStrike = 1080,
        Thrust = 1133,
        ThrustDebuff = 1168,
        Thunderstorm = 1022,
        Tolerance = 1153,
        Toughness = 1132,
        TribulationCaster = 1075,
        TribulationTarget = 1059,
        TrueFear = 1109,
        Unknown2 = 1179,
        UnknownDebuff = 1189,
        UnknownGoblin = 1182,
        UnknownRedDrop = 1183,
        UnknownStar = 1184,
        UnknownTomato = 1163,
        UraliTranceTonic = 1174,
        VampiricEmbrace = 1087,
        Veterinary = 1101,
        Warcry = 1148,
        Warding = 1074,
        Weaken = 1042,
        Webbing = 1107,
        Whispering = 1159,
        WhiteTigerForm = 1150,
        WraithForm = 1124
    }

    /**
     * BuffDebuffs enumeration
     * Represents various buff and debuff effects in the game
     * Note: This appears to be the same as Abilities based on the documentation
     */
    declare enum BuffDebuffs {
        AchievePerfection = 1009,
        ActiveMeditation = 1013,
        Agility = 1045,
        AnimalForm = 1034,
        AnticipateHit = 1147,
        ArcaneEmpowerment = 1026,
        ArchProtection = 1030,
        ArmorPierce = 1121,
        AttuneWeapon = 1021,
        AuraOfNausea = 1110,
        BarakoDraftOfMight = 1173,
        BarrabHemolymphConcentrate = 1170,
        Berserk = 1052,
        Bleed = 1039,
        Bless = 1048,
        Block = 1066,
        BloodOathCaster = 1014,
        BloodOathCurse = 1015,
        BloodwormAnemia = 1115,
        Boarding = 1166,
        Bodyguard = 1151,
        BoneBreaker = 1178,
        BoneBreakerImmune = 1181,
        CaddelliteInfused = 1186,
        CalledShot = 1140,
        CityTradeDeal = 1126,
        Clumsy = 1040,
        CombatTraining = 1160,
        Conduit = 1143,
        Confidence = 1093,
        ConsecrateWeapon = 1082,
        CorpseSkin = 1016,
        CounterAttack = 1095,
        CriminalStatus = 1120,
        Cunning = 1046,
        Curse = 1043,
        CurseWeapon = 1088,
        DeathRay = 1154,
        DeathRayDebuff = 1155,
        DeathStrike = 1006,
        DefenseMastery = 1067,
        DespairCaster = 1068,
        DespairTarget = 1060,
        Disarm = 1077,
        Disguised = 1033,
        DismountPrevention = 1001,
        DivineFury = 1010,
        DragonTurtleDebuff = 1165,
        DualWield = 1065,
        ElementalFury = 1138,
        ElementalFuryDebuff = 1139,
        Enchant = 1091,
        EnchantedSummoning = 1157,
        EnemyOfOne = 1011,
        EnemyOfOneDebuff = 1084,
        EssenceOfWind = 1023,
        EtherealBurst = 1144,
        EtherealVoyage = 1024,
        Evasion = 1094,
        EvilOmen = 1007,
        FactionStatLoss = 1118,
        FanDancerFanFire = 1105,
        FeebleMind = 1041,
        Feint = 1079,
        FeintDebuff = 1185,
        FishPie = 1062,
        FistsOfFury = 1169,
        Fly = 1054,
        FocusedEye = 1136,
        ForceArrow = 1076,
        GazeDespair = 1112,
        GiftOfLife = 1025,
        GiftOfRenewal = 1020,
        GrapesOfWrath = 1083,
        Healing = 1069,
        HeatOfBattleStatus = 1119,
        HeightenedSenses = 1152,
        HidingAndOrStealth = 1012,
        HiryuPhysicalResistance = 1113,
        HitLowerAttack = 1063,
        HitLowerDefense = 1064,
        HonorableExecution = 1092,
        Honored = 1103,
        HonoredDebuff = 1008,
        HorrificBeast = 1085,
        HowlOfCacophony = 1111,
        Humility = 1129,
        HumilityDebuff = 1127,
        ImmolatingWeapon = 1090,
        Incognito = 1032,
        InjectedStrike = 1162,
        InjectedStrikeDebuff = 1161,
        Inspire = 1055,
        Intuition = 1156,
        Invigorate = 1056,
        Invisibility = 1036,
        JukariBurnPoiltice = 1171,
        Knockout = 1141,
        KurakAmbushersEssence = 1172,
        LichForm = 1086,
        LightningStrike = 1096,
        MagicReflection = 1031,
        ManaPhase = 1104,
        ManaShield = 1146,
        MassCurse = 1044,
        MassSleep = 1053,
        MedusaStone = 1108,
        Mindrot = 1017,
        MomentumStrike = 1097,
        MortalStrike = 1027,
        MysticWeapon = 1145,
        MysticalPolymorphTotem = 1188,
        NightSight = 1005,
        NoRearm = 1002,
        Onslaught = 1137,
        OrangePetals = 1098,
        PainSpike = 1018,
        Paralyze = 1037,
        Perfection = 1102,
        Perseverance = 1058,
        Pierce = 1134,
        PlayingTheOdds = 1135,
        PlayingTheOddsDebuff = 1164,
        Poison = 1038,
        PoisonImmunity = 1100,
        Polymorph = 1035,
        Potency = 1167,
        PotionGloriousFortune = 1187,
        Protection = 1029,
        PsychicAttack = 1081,
        Rage = 1106,
        RageFocusingBuff = 1073,
        RageFocusingDebuff = 1072,
        Rampage = 1130,
        ReactiveArmor = 1028,
        ReaperForm = 1089,
        Resilience = 1057,
        RoseOfTrinsic = 1099,
        RotwormBloodDisease = 1116,
        RuneBeetleCorruption = 1114,
        SakkhraProphylaxis = 1175,
        SavingThrow = 1142,
        Shadow = 1149,
        ShieldBash = 1158,
        SkillUseDelay = 1117,
        Sleep = 1049,
        Sparks = 1176,
        SpellFocusingBuff = 1070,
        SpellFocusingDebuff = 1071,
        SpellPlague = 1051,
        Spirituality = 1128,
        SplinteringEffect = 1122,
        Stagger = 1131,
        StoneForm = 1050,
        Strangle = 1019,
        Strength = 1047,
        Surge = 1078,
        Swarm = 1177,
        SwarmImmune = 1180,
        SwingSpeedDebuff = 1123,
        TalonStrike = 1080,
        Thrust = 1133,
        ThrustDebuff = 1168,
        Thunderstorm = 1022,
        Tolerance = 1153,
        Toughness = 1132,
        TribulationCaster = 1075,
        TribulationTarget = 1059,
        TrueFear = 1109,
        Unknown2 = 1179,
        UnknownDebuff = 1189,
        UnknownGoblin = 1182,
        UnknownRedDrop = 1183,
        UnknownStar = 1184,
        UnknownTomato = 1163,
        UraliTranceTonic = 1174,
        VampiricEmbrace = 1087,
        Veterinary = 1101,
        Warcry = 1148,
        Warding = 1074,
        Weaken = 1042,
        Webbing = 1107,
        Whispering = 1159,
        WhiteTigerForm = 1150,
        WraithForm = 1124
    }

    /**
     * Constant enumeration
     * Represents various constant values used throughout the scripting API
     * Note: Specific values not provided in documentation
     */
    declare enum Constant {
        // Values would be defined here based on actual constants
        // This is a placeholder for the Constant enumeration
    }

    /**
     * Directions enumeration
     * Represents the eight possible directions an entity can face
     */
    declare enum Directions {
        North = 0,
        Northeast = 1,
        East = 2,
        Southeast = 3,
        South = 4,
        Southwest = 5,
        West = 6,
        Northwest = 7
    }

    /**
     * Layers enumeration
     * Represents the equipment layers for items
     */
    declare enum Layers {
        Invalid = 0,
        OneHandedWeapon = 1,
        TwoHandedWeapon = 2,
        Shoes = 3,
        Pants = 4,
        Shirt = 5,
        Helmet = 6,
        Gloves = 7,
        Ring = 8,
        Talisman = 9,
        Necklace = 10,
        Hair = 11,
        Waist = 12,
        Torso = 13,
        Bracelet = 14,
        Face = 15,
        Beard = 16,
        Tunic = 17,
        Earrings = 18,
        Arms = 19,
        Cloak = 20,
        Backpack = 21,
        Robe = 22,
        Skirt = 23,
        Legs = 24,
        Mount = 25,
        ShopBuy = 26,
        ShopSell = 27,
        ShopRestock = 28,
        ShopSellHides = 29
    }

    /**
     * MessageType enumeration
     * Represents different types of game messages
     */
    declare enum MessageType {
        // Values would be defined here based on actual message types
        // This is a placeholder for the MessageType enumeration
    }

    /**
     * Notorieties enumeration
     * Represents the notoriety levels of entities
     */
    declare enum Notorieties {
        Innocent = 1,
        Friend = 2,
        Gray = 3,
        Criminal = 4,
        Enemy = 5,
        Murderer = 6,
        Invulnerable = 7
    }

    /**
     * SearchEntityOptions enumeration
     * Represents options for entity search operations
     */
    declare enum SearchEntityOptions {
        Any = 1,
        Enemy = 2,
        Murderer = 4,
        Criminal = 8,
        Gray = 16,
        Innocent = 32,
        Unfriendly = 64,
        Friend = 128,
        Invulnerable = 256
    }

    /**
     * SearchEntityRangeOptions enumeration
     * Represents range options for entity search operations
     */
    declare enum SearchEntityRangeOptions {
        Next = 0,
        Previous = 1,
        Nearest = 2,
        Closest = 3
    }

    /**
     * SearchEntityTypeOptions enumeration
     * Represents type options for entity search operations
     */
    declare enum SearchEntityTypeOptions {
        Any = 0,
        Human = 1,
        NonHuman = 2
    }

    /**
     * SkillLock enumeration
     * Represents skill lock states
     */
    declare enum SkillLock {
        Up = 0,
        Down = 1,
        Locked = 2
    }

    /**
     * Skills enumeration
     * Represents all available skills in the game
     */
    declare enum Skills {
        Alchemy = 0,
        Anatomy = 1,
        AnimalLore = 2,
        AnimalTaming = 35,
        Archery = 31,
        ArmsLore = 4,
        Begging = 6,
        Blacksmith = 7,
        Bushido = 52,
        Camping = 10,
        Carpentry = 11,
        Cartography = 12,
        Chivalry = 51,
        Cooking = 13,
        DetectHidden = 14,
        Discordance = 15,
        EvalInt = 16,
        Fencing = 42,
        Fishing = 18,
        Fletching = 8,
        Focus = 50,
        Forensics = 19,
        Healing = 17,
        Herding = 20,
        Hiding = 21,
        Imbuing = 56,
        Inscribe = 23,
        ItemID = 3,
        Lockpicking = 24,
        Lumberjacking = 44,
        Macing = 41,
        Magery = 25,
        MagicResist = 26,
        Meditation = 46,
        Mining = 45,
        Musicianship = 29,
        Mysticism = 55,
        Necromancy = 49,
        Ninjitsu = 53,
        Parry = 5,
        Peacemaking = 9,
        Poisoning = 30,
        Provocation = 22,
        RemoveTrap = 48,
        Snooping = 28,
        Spellweaving = 54,
        SpiritSpeak = 32,
        Stealing = 33,
        Stealth = 47,
        Swords = 40,
        Tactics = 27,
        Tailoring = 34,
        TasteID = 36,
        Throwing = 57,
        Tinkering = 37,
        Tracking = 38,
        Veterinary = 39,
        Wrestling = 43
    }

    /**
     * Spells enumeration
     * Represents various spells in the game
     * Note: Incomplete in documentation
     */
    declare enum Spells {
        Agility = 9,
        AirElemental = 60,
        AnimalForm = 503,
        AnimateDead = 101,
        AnimatedWeapon = 684,
        AnticipateHit = 716,
        ArcaneCircle = 601,
        ArcaneEmpowerment = 616,
        ArchCure = 25,
        ArchProtection = 26,
        Attunement = 604,
        Backstab = 506,
        BladeSpirits = 33,
        Bless = 17,
        BloodOath = 102,
        Boarding = 745,
        Bodyguard = 735,
        Bombard = 689,
        CalledShot = 732,
        ChainLightning = 49,
        CleanseByFire = 201,
        CleansingWinds = 688,
        CloseWounds = 202,
        Clumsy = 1,
        CombatTraining = 744,
        CommandUndead = 711,
        Conduit = 712,
        Confidence = 402,
        ConsecrateWeapon = 203,
        CorpseSkin = 103,
        CounterAttack = 404,
        CreateFood = 2,
        Cunning = 10,
        Cure = 11,
        Curse = 27,
        CurseWeapon = 104,
        DeathRay = 707,
        DeathStrike = 502,
        Despair = 706,
        Dispel = 0 // Note: Incomplete in documentation
    }

    declare enum Virtues {
        Honor = 1,
        Sacrifice = 2,
        Valor = 3,
        Compassion = 4,
        Justice = 5,
        Humility = 6,
        Spirituality = 7
    }

}

